# To add fields, make a new schema file in this directory
# and change the schema setting in _config.yml to its name
dataset_fields:
  - field_name: title
    label: Title
    datajson: title
  - field_name: organization
    label: Organization
    form_template: form/organization.html
    datajson: publisher.name
  - field_name: notes
    label: Description
    form_template: form/textarea.html
    datajson: description
  - field_name: license
    label: License
    form_template: form/license.html
    datajson: license
  - field_name: dataset_name
    label: Dataset_name
    datajson: dataset_name
  - field_name: location
    label: Location
    datajson: location
  - field_name: start_date
    label: Start Date
    datajson: start_date
  - field_name: end_date
    label: End Date
    datajson: end_date
  - field_name: dataset_type
    label: Dataset Type
    datajson: dataset_type
  - field_name: sensor_type
    label: Sensor Type
    datajson: sensor_type
  - field_name: size
    label: Size
    datajson: size
  - field_name: dataset_format
    label: Dataset Format
    datajson: dataset_format
  - field_name: other_format
    label: Other Available Format
    datajson: other_format
  - field_name: number_participants
    label: Number of Participants
    datajson: number_participants
  - field_name: language
    label: Language
    datajson: language
  - field_name: collection_name
    label: Collection Name
    datajson: collection_name
  - field_name: project_url
    label: Project URL
    datajson: project_url
  - field_name: category
    label: Domain
    form_template: form/category.html
    display_template: display/category.html
    datajson: category
  - field_name: 5_stars
    label: 5-Stars
    datajson: 5_stars
  - field_name: publication_date
    label: Publication Date
    datajson: publication_date
  - field_name: identifier
    label: Identifier
    datajson: identifier
  - field_name: request_contact
    label: Download Request Contact
    datajson: request_contact

resource_fields:
  - field_name: name
    label: Resource Name
    datajson: distribution.title
  - field_name: url
    label: URL
    datajson: distribution.downloadURL
  - field_name: format
    label: Format
    datajson: distribution.format
    form_template: form/dropdown.html
    values:
      - api
      - csv
      - rdf
      - json
      - geojson
      - html
      - kml
      - kmz
      - shp
      - xml
      - pdf

organization_fields:
  - field_name: title
    label: Title
  - field_name: description
    label: Description
  - field_name: logo
    label: Logo

category_fields:
  - field_name: name
    label: Name
  - field_name: logo
    label: Logo
  - field_name: logo_credit
    label: Logo Credit
  - field_name: featured
    label: Featured on Homepage
    form_template: form/checkbox.html
